config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',  
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'products#index'

  get '/users/mypage', to: 'users#mypage'
  get '/users/sign_out', to: 'users#sign_out'

  get '/users/information', to: 'users#information'
  get '/users/sms_confirmation', to: 'users#sms_confirmation'
  post '/users/sms_confirmation', to: 'users#sms_confirmation'
  get '/users/address', to: 'users#address'
  post '/users/address', to: 'users#address'
  get '/users/payment', to: 'users#payment'
  post '/users/payment', to: 'users#payment'
  get '/users/complete', to: 'users#complete'
  post '/users/complete', to: 'users#complete'

  get '/users/mypage/identification', to: 'users#identification'
  get '/users/credit_confirmation', to: 'users#credit_confirmation'
  get '/users/:id', to: "profile#edit"
  patch '/users/:id', to: "profile#create"


  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      match 'search' => 'products#search', via: [:get, :post]
    end
    resources :purchase, only: [:new, :create] 
  end

  resources :users, except: :show
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

        def self.find_for_oauth(auth)
          user = User.where(uid: auth.uid, provider: auth.provider).first
      
          unless user
            user = User.create(
              uid:      auth.uid,
              provider: auth.provider,
              nickname:     auth.info.name,
              email:    auth.info.email,
              password: Devise.friendly_token[0, 20]
            )
          end

          user
        end
      
        def sns
          @user = User.new(
            nickname: session[:nickname],
            email: session[:email],
            password: session[:password],
            password_confirmation: session[:password],
            )
        end
      
        def create
          super
          @user.uid = session[:uid]
          @user.provider = session[:provider]
          @user.save
        end

  has_many :bought_plural, class_name: "Purchase", dependent: :destroy
  has_many :sold_plural, class_name: "Purchase", dependent: :destroy
  has_many :products
  #  取引成立前のコメント機能は後ほど実装予定
  # has_many :comments
  # has_many :products, through: :comments
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
  has_one :card
  has_many :purchases
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true, length: { minimum: 6 }
  validates :nickname, presence: true
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :birthday, presence: true
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  validates :phone, presence: true, format: { with: VALID_PHONE_REGEX }

  def valid_information?
    valid?
    excluded_column = :phone
    errors.delete(excluded_column)
    errors.empty?
  end

  def valid_phone?
    valid?
    excluded_columns = [:email, :password, :password_confirmation, :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :birthday]
    excluded_columns.each{|column| errors.delete(column)}
    errors.empty?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    callback_from :facebook
  end

  def google_oauth2
    callback_from :google
  end

  private

  def callback_from(provider)
    provider = provider.to_s
    @user = User.find_for_oauth(request.env['omniauth.auth'])
 
    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session[:nickname] = @user.nickname
      session[:email] = @user.email
      session[:password] = @user.password
      session[:provider] = @user.provider
      session[:uid] = @user.uid

      if provider == "google"
        redirect_to user_google_oauth2_omniauth_callback_path
      else
        redirect_to user_facebook_omniauth_callback_path
      end
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController


  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # def create
  #   super
  #   user = User.find_by(email: params[:user][:email])
  #   if user
  #     if user.valid_password?(params[:user][:password]) 
  #       # sign_in_and_redirect user
  #       redirect_to root_path
  #     else
  #       flash[:error] =  "Please enter the valid password."
  #     end
  #   end
  # end

  # def new
  #   @login = Session.new
  # end

  # def create
  #   @login = Session.new(email: params[:session][:email], password: params[:session][:password])
  #   if @login.save && (@user = User.find_by(email: @login.email))&& @user.authenticate(@login.password)
  #     redirect_to users_path
  #   else
  #     render :new
  #   end
  # end


end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update]
  before_action :authenticate_user!, only: [:mypage,:identification,:sign_out, :credit_confirmation]
  
  def create 
    @user = User.create(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def mypage
  end
  
  def sign_out
  end

  def information
    @user = User.new
  end

  def sms_confirmation
    # sessionにフォーム情報を格納
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:family_name] = user_params[:family_name]
    session[:first_name] = user_params[:first_name]
    session[:family_name_kana] = user_params[:family_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana]
    # フォームデータを元にDateオブジェクトを作成してからsessionに格納
    unless user_params["birthday(1i)"].blank? || user_params["birthday(2i)"].blank? || user_params["birthday(3i)"].blank?
      session[:birthday] = Date.new(user_params["birthday(1i)"]&.to_i, user_params["birthday(2i)"]&.to_i, user_params["birthday(3i)"]&.to_i)
    end
    # /users/addressでユーザー情報の表示をするため、そこまではuser_paramsを使ってインスタンスを作って渡していく形でデータを保持
    @user = User.new(user_params)
    if @user.valid_information?
      render :sms_confirmation
    else
      @messages = @user.errors.full_messages
      render :information
    end
  end

  def address
    session[:phone] = user_params[:phone]
    @user = User.new(
      family_name: session[:family_name],
      first_name: session[:first_name],
      family_name_kana: session[:family_name_kana],
      first_name_kana: session[:first_name_kana],
      phone: session[:phone]
    )
    if @user.valid_phone?
      @address = @user.build_address
      render :address
    else
      @messages = @user.errors.full_messages
      render :sms_confirmation
    end
  end

  def payment
    session[:postal_code] = user_params[:address_attributes][:postal_code]
    session[:prefecture_id] = user_params[:address_attributes][:prefecture_id]
    session[:city] = user_params[:address_attributes][:city]
    session[:block] = user_params[:address_attributes][:block]
    session[:building] = user_params[:address_attributes][:building]
    session[:sub_phone] = user_params[:address_attributes][:sub_phone]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      family_name: session[:family_name],
      first_name: session[:first_name],
      family_name_kana: session[:family_name_kana],
      first_name_kana: session[:first_name_kana],
      birthday: session[:birthday],
      phone: session[:phone]
    )
    @address = @user.build_address(user_params[:address_attributes])
    if @address.valid_address?
      @card = Card.new
      render :payment
    else
      @messages = @address.errors.full_messages
      render :address
    end
  end

  def complete
    session[:number] = card_params[:number]
    session[:expiration_date] = Date.new(card_params["expiration_date(1i)"]&.to_i, card_params["expiration_date(2i)"]&.to_i + 1) - 1
    session[:security_code] = card_params[:security_code]

    @card = Card.new(card_params)
    unless @card.valid_card?
      @messages = @card.errors.full_messages
      render :payment and return
    end
    
    # sessionに貯めてきたデータでUser, Address, CardをCreateする
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      family_name: session[:family_name],
      first_name: session[:first_name],
      family_name_kana: session[:family_name_kana],
      first_name_kana: session[:first_name_kana],
      birthday: session[:birthday],
      phone: session[:phone]
    )
    @messages = @user.errors.full_messages unless @user.valid?
    redirect_to new_user_registration_path and return unless @user.save

    @address = @user.build_address(
      postal_code: session[:postal_code],
      prefecture_id: session[:prefecture_id],
      city: session[:city],
      block: session[:block],
      building: session[:building],
      sub_phone: session[:sub_phone]
    )
    @messages = @address.errors.full_messages unless @address.valid?
    redirect_to new_user_registration_path and return unless @address.save

    @card = @user.build_card(
      number: session[:number],
      expiration_date: session[:expiration_date],
      security_code: session[:security_code]
    )
    @messages = @card.errors.full_messages unless @card.valid?
    redirect_to new_user_registration_path and return unless @card.save

    render :complete and return
  end
  


  def identification
  end
  
  def credit_confirmation
  end

  def update
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :family_name, :first_name, :family_name_kana, :first_name_kana, :birthday, :phone, :image, :profile, address_attributes: [:postal_code, :prefecture_id, :city, :block, :building, :sub_phone])
  end

  def address_params
    params.require(:address).permit(:postal_code, :prefecture_id, :city, :block, :building, :sub_phone, :user_id)
  end

  def card_params
    params.require(:card).permit(:number, :expiration_date, :security_code, :user_id)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/address.html.haml
.signup-header
  .signup-header__block
  .signup-header__area
    .signup-header__area__logo
    .signup-header__area__figure
      .signup-header__area__figure__information
        .signup-header__area__figure__information__title
          会員情報
        .signup-header__area__figure__information__under
          .signup-header__area__figure__information__under__dot
          .signup-header__area__figure__information__under__bar-sms

      .signup-header__area__figure__sms
        .signup-header__area__figure__sms__title
          電話番号認証
        .signup-header__area__figure__sms__under
          .signup-header__area__figure__sms__under__dot-sms
          .signup-header__area__figure__sms__under__bar-address

      .signup-header__area__figure__address
        .signup-header__area__figure__address__title-address
          お届け先住所
        .signup-header__area__figure__address__under
          .signup-header__area__figure__address__under__dot-address
          .signup-header__area__figure__address__under__bar

      .signup-header__area__figure__payment
        .signup-header__area__figure__payment__title
          支払い方法
        .signup-header__area__figure__payment__under
          .signup-header__area__figure__payment__under__dot
          .signup-header__area__figure__payment__under__bar
      .signup-header__area__figure__complete
        .signup-header__area__figure__complete__title
          完了
        .signup-header__area__figure__complete__under
          .signup-header__area__figure__complete__under__dot

.address
  .address__areaup
    .address__areaup__logo
      住所入力
  .address__areadown
    - if @messages
      - @messages.each do |message|
        %p
          = message
    .address__areadown__form
      
      = form_with model: @user, url: users_payment_path, local: true do |f|
        .field
          = f.label :お名前, class: 'title'
          = f.label :必須, class: 'need'
          %br/
          = f.text_field :family_name, placeholder: "例)山田", class: 'forms'
          = f.text_field :first_name, placeholder: "例)彩", class: 'forms'

        .field
          = f.label :お名前カナ, class: 'title'
          = f.label :必須, class: 'need'
          %br/
          = f.text_field :family_name_kana, placeholder: "例)ヤマダ", class: 'forms'
          = f.text_field :first_name_kana, placeholder: "例)アヤ", class: 'forms'
        
        = f.fields_for :address do |a|
          .field
            = a.label :postal_code, '郵便番号', class: 'title'
            = a.label :必須, class: 'need'
            %br/
            = a.text_field :postal_code, placeholder: "例)123-4567", class: 'forms'

          .field
            = a.label :prefecture_id, '都道府県', class: 'title'
            = a.label :必須, class: 'need'
            %br/
            = a.collection_select :prefecture_id, Prefecture.all, :id, :name
              
          .field
            = a.label :city, '市区町村', class: 'title'
            = a.label :必須, class: 'need'
            %br/
            = a.text_field :city, placeholder: "例)横浜市緑区", class: 'forms'

          .field
            = a.label :block, '番地', class: 'title'
            = a.label :必須, class: 'need'
            %br/
            = a.text_field :block, placeholder: "例)青山1-1-1", class: 'forms'

          .field
            = a.label :building, '建物名', class: 'title'
            = a.label :任意, class: 'any'
            %br/
            = a.text_field :building, placeholder: "例)柳ビル103" ,class: 'forms'

          .field
            = a.label :sub_phone, '電話', class: 'title'
            = a.label :任意, class: 'any'
            %br/
          = a.text_field :sub_phone, placeholder: "例)09012345678" ,class: 'forms'


        .actions
          = f.submit "次へ進む", class:'nextsubmit'

= render 'shared/sign_up_footer'

app/views/users/edit_profile.html.haml
= render 'shared/header'
= render 'shared/exhibitation'
- flash.each do |message_type, message|
  .alert{class: "alert-#{message_type}"}
    .message
      = message
%main.wrapper_all 
  .left_contents
    = render partial: 'shared/navigations'
  .right_contents
    .profile-title
      プロフィール
    .bgimage
      .person
        %div.thumbnail= image_tag asset_path('thumbnail.png')
      = form_for(@user, url: user_path(@user.id), method: :patch) do |f|
        = f.text_field :nickname, :class => "profile-text", :value => @user.nickname, :style => "padding: 5px;"
        = f.text_area :profile, :class => "text-area", :placeholder => "例）こんにちは☆ご覧いただきありがとうございます！", :rows => "5"
        = f.submit "登録", :class => "submit_changes"
         
    .bottom-boxes

= render 'shared/footer'

app/views/users/information.html.haml
.signup-header
  .signup-header__block
  .signup-header__area
    .signup-header__area__logo
    .signup-header__area__figure
      .signup-header__area__figure__information
        .signup-header__area__figure__information__title-info
          会員情報
        .signup-header__area__figure__information__under
          .signup-header__area__figure__information__under__dot
          .signup-header__area__figure__information__under__bar

      .signup-header__area__figure__sms
        .signup-header__area__figure__sms__title
          電話番号認証
        .signup-header__area__figure__sms__under
          .signup-header__area__figure__sms__under__dot
          .signup-header__area__figure__sms__under__bar

      .signup-header__area__figure__address
        .signup-header__area__figure__address__title
          お届け先住所
        .signup-header__area__figure__address__under
          .signup-header__area__figure__address__under__dot
          .signup-header__area__figure__address__under__bar

      .signup-header__area__figure__payment
        .signup-header__area__figure__payment__title
          支払い方法
        .signup-header__area__figure__payment__under
          .signup-header__area__figure__payment__under__dot
          .signup-header__area__figure__payment__under__bar
      .signup-header__area__figure__complete
        .signup-header__area__figure__complete__title
          完了
        .signup-header__area__figure__complete__under
          .signup-header__area__figure__complete__under__dot

.information
  .information__areaup
    .information__areaup__logo
      会員情報入力
  .information__areadown
    .information__areadown__form
      - if @messages
        - @messages.each do |message|
          %p
            = message
      = form_with model: @user, url: users_sms_confirmation_path, local: true do |f|
        .field
          = f.label :nickname, 'ニックネーム', class: 'title'
          = f.label :必須, class: 'need'
          %br/
          = f.text_field :nickname, placeholder: "例)メルカリ太郎", class: 'forms'

        .field
          = f.label :email, 'メールアドレス', class: 'title'
          = f.label :必須, class: 'need'
          %br/
          = f.text_field :email, placeholder: "PC・携帯どちらでも可", class: 'forms'

        .field
          = f.label :password, 'パスワード', class: 'title'
          = f.label :password, '必須', class: 'need'
          %br/
          = f.password_field :password, placeholder: "6文字以上", class: 'forms'

        .field
          = f.label :password_confirmation, 'パスワード (確認)', class: 'title'
          = f.label :必須, class: 'need'
          %br/
          = f.password_field :password_confirmation, placeholder: "6文字以上", class: 'forms'

        .person
          本人確認
        .text
          安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。

        .field
          = f.label "お名前(全角)", class: 'title'
          = f.label :必須, class: 'need'
          .nameform
            = f.text_field :family_name, placeholder: "例)山田", class: 'name'
            = f.text_field :first_name, placeholder: "例)彩" , class: 'names'

        .field
          = f.label "お名前カナ(全角)", class: 'title'
          = f.label :必須, class: 'need'
          .nameform
            = f.text_field :family_name_kana, placeholder: "例)ヤマダ", class: 'name'
            = f.text_field :first_name_kana, placeholder: "例)アヤ", class: 'names'

          = f.label :birthday, '生年月日', class: 'title'
          = f.label :必須, class: 'need'
          .birthday
            = raw sprintf(f.date_select(:birthday, prompt: '--', start_year: Time.now.year, end_year: 1900, use_month_numbers: true, date_separator: '%s'),'年','月')
            日
          .personalinfo
            ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
        .robot
          -# = recaptcha_tags
        
        .agreement
          「次へ進む」のボタンを押すことにより、
          %a{ href: "" } 利用規約
          に同意したものとみなします。

        .actions
          = f.submit "次へ進む", class: 'nextsubmit'

        .about
          = link_to "", class: "about" do
            本人情報の登録について
            = icon("fas", "angle-right", class:"angle")

= render 'shared/sign_up_footer'

app/views/users/payment.html.haml
.signup-header
  .signup-header__block
  .signup-header__area
    .signup-header__area__logo
    .signup-header__area__figure
      .signup-header__area__figure__information
        .signup-header__area__figure__information__title
          会員情報
        .signup-header__area__figure__information__under
          .signup-header__area__figure__information__under__dot
          .signup-header__area__figure__information__under__bar-sms

      .signup-header__area__figure__sms
        .signup-header__area__figure__sms__title
          電話番号認証
        .signup-header__area__figure__sms__under
          .signup-header__area__figure__sms__under__dot-sms
          .signup-header__area__figure__sms__under__bar-address

      .signup-header__area__figure__address
        .signup-header__area__figure__address__title
          お届け先住所
        .signup-header__area__figure__address__under
          .signup-header__area__figure__address__under__dot-address
          .signup-header__area__figure__address__under__bar-payment

      .signup-header__area__figure__payment
        .signup-header__area__figure__payment__title-payment
          支払い方法
        .signup-header__area__figure__payment__under
          .signup-header__area__figure__payment__under__dot-payment
          .signup-header__area__figure__payment__under__bar
      .signup-header__area__figure__complete
        .signup-header__area__figure__complete__title
          完了
        .signup-header__area__figure__complete__under
          .signup-header__area__figure__complete__under__dot

.payment
  .payment__areaup
    .payment__areaup__logo
      クレジットカード情報入力
  .payment__areadown
    - if @messages
      - @messages.each do |message|
        %p
          = message
    .payment__areadown__form
      = form_with model: @card, url: users_complete_path, local: true do |f|
        .field
          = f.label :number, 'カード番号', class: 'title'
          = f.label :必須, class: 'need'
          %br/
          = f.text_field :number, placeholder: "半角数字のみ", class: 'forms'
          .cards
          = f.label :expiration_date, '有効期限', class: 'title'
          = f.label :必須, class: 'need'
          .pulldown
            = raw sprintf(f.date_select(:expiration_date, prompt: '--', start_year: Time.now.year, end_year: Time.now.year + 15, use_two_digit_numbers: true, discard_day: true, order: [:month, :year], date_separator: '%s'), '月')
            年
          .field
          = f.label :security_code, 'セキュリティコード', class: 'title'
          = f.label :必須, class: 'need'
          %br/
          = f.text_field :security_code, placeholder: "カード裏面の4桁もしくは３桁の数字", class: 'forms'
          .question
            =link_to "", class: "question" do
              = icon("far", "question-circle", class: "question")
              カード裏面の番号とは？

          .actions
          = f.submit "次へ進む", class: 'next_submit'

= render 'shared/sign_up_footer'

app/views/users/sms_confirmation.html.haml
.signup-header
  .signup-header__block
  .signup-header__area
    .signup-header__area__logo
    .signup-header__area__figure
      .signup-header__area__figure__information
        .signup-header__area__figure__information__title
          会員情報
        .signup-header__area__figure__information__under
          .signup-header__area__figure__information__under__dot
          .signup-header__area__figure__information__under__bar-sms

      .signup-header__area__figure__sms
        .signup-header__area__figure__sms__title-sms
          電話番号認証
        .signup-header__area__figure__sms__under
          .signup-header__area__figure__sms__under__dot-sms
          .signup-header__area__figure__sms__under__bar

      .signup-header__area__figure__address
        .signup-header__area__figure__address__title
          お届け先住所
        .signup-header__area__figure__address__under
          .signup-header__area__figure__address__under__dot
          .signup-header__area__figure__address__under__bar

      .signup-header__area__figure__payment
        .signup-header__area__figure__payment__title
          支払い方法
        .signup-header__area__figure__payment__under
          .signup-header__area__figure__payment__under__dot
          .signup-header__area__figure__payment__under__bar
      .signup-header__area__figure__complete
        .signup-header__area__figure__complete__title
          完了
        .signup-header__area__figure__complete__under
          .signup-header__area__figure__complete__under__dot

.confirmation
  .confirmation__areaup
    .confirmation__areaup__logo
      電話番号の確認
  
  .confirmation__areadown
    - if @messages
      - @messages.each do |message|
        %p
          = message
    .confirmation__areadown__phonenumber
      = form_with model: @user, url: users_address_path, local: true do |f|
        .field
          = f.label :phone, '携帯電話の番号', class: 'label__phonenumber'
          %br/
          = f.phone_field :phone, autofocus: true, placeholder: "携帯電話の番号を入力" , required: "", class: 'form__phonenumber'
          .confirmation__areadown__text
            本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
        .actions
          = f.submit "SMSを送信する", class: 'sms_submit'
        .confirmation__areadown__phonesubmit
          ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
        .confirmation__areadown__reason
          = link_to "", class: "reason" do
            電話番号の確認が必要な理由
            = icon("fas", "angle-right", class:"angle")

= render 'shared/sign_up_footer'