config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',  
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'products#index'

  get '/users/mypage', to: 'users#mypage'
  get '/users/sign_out', to: 'users#sign_out'

  get '/users/information', to: 'users#information'
  get '/users/sms_confirmation', to: 'users#sms_confirmation'
  post '/users/sms_confirmation', to: 'users#sms_confirmation'
  get '/users/address', to: 'users#address'
  post '/users/address', to: 'users#address'
  get '/users/payment', to: 'users#payment'
  post '/users/payment', to: 'users#payment'
  get '/users/complete', to: 'users#complete'
  post '/users/complete', to: 'users#complete'

  get '/users/mypage/identification', to: 'users#identification'
  get '/users/credit_confirmation', to: 'users#credit_confirmation'
  get '/users/:id', to: "profile#edit"
  patch '/users/:id', to: "profile#create"


  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      match 'search' => 'products#search', via: [:get, :post]
    end
    resources :purchase, only: [:new, :create] 
  end

  resources :users, except: :show
end

app/views/shared/_breadcrumbs.html.haml
.breadcrumbs-wrapper
  = breadcrumbs separator: "<i class='fas fa-angle-right' style='margin: 0 8px;color: #888;'></i>"

app/views/shared/_exhibitation.html.haml
.exhibitation 
  = link_to new_product_path, class: "exhibit-btn" do
    .exhibitation__logo
      出品
    .exhibitation__icon
      = icon("far", "camera fa-4x",class:"camera")

app/views/shared/_footer.html.haml
.footer
  .footer__top
    .footer__top__area
      .footer__top__area__img
  .footer__bottom
    .footer__bottom__area
      .footer__bottom__area__about
        .footer__bottom__area__about__title
          =link_to "", class: "about" do
            メルカリについて
        .footer__bottom__area__about__company
          =link_to "", class: "about" do
            会社概要(運営会社)
        .footer__bottom__area__about__recruit
          =link_to "", class: "about" do
            採用情報
        .footer__bottom__area__about__pless
          =link_to "", class: "about" do
            プレスリリース
        .footer__bottom__area__about__blog
          =link_to "", class: "about" do
            公式ブログ
        .footer__bottom__area__about__logoguideline
          =link_to "", class: "about" do
            メルカリロゴ利用ガイドライン
        .footer__bottom__area__about__logos
          .footer__bottom__area__about__logos__twitter
            =link_to "https://twitter.com/", class: "twitter" do
              = icon("far", "twitter fa-2x",class:"twitter")
          .footer__bottom__area__about__logos__facebook
            =link_to "https://www.facebook.com/", class: "facebook" do
              = icon("far", "facebook fa-2x",class:"facebook")
        .footer__bottom__area__about__logowhite
      .footer__bottom__area__helpguide
        .footer__bottom__area__helpguide__title
          =link_to "", class: "helpguide" do
            ヘルプ&ガイド
        .footer__bottom__area__helpguide__guide
          =link_to "", class: "helpguide" do
            メルカリガイド
        .footer__bottom__area__helpguide__rakuraku
          =link_to "", class: "helpguide" do
            らくらくメルカリ便
        .footer__bottom__area__helpguide__yuyu
          =link_to "", class: "helpguide" do
            ゆうゆうメルカリ便
        .footer__bottom__area__helpguide__ogata
          =link_to "", class: "helpguide" do
            大型メルカリ便
        .footer__bottom__area__helpguide__carguide
          =link_to "", class: "helpguide" do
            車体取引ガイド
        .footer__bottom__area__helpguide__declaration
          =link_to "", class: "helpguide" do
            メルカリあんしん・あんぜん宣言！
        .footer__bottom__area__helpguide__faker
          =link_to "", class: "helpguide" do
            偽ブランド品撲滅への取り組み
        .footer__bottom__area__helpguide__box
          =link_to "", class: "helpguide" do
            メルカリボックス
      .footer__bottom__area__privacyleft
        .footer__bottom__area__privacyleft__title
          =link_to "", class: "privacyleft" do
            プライバシーと利用規約
        .footer__bottom__area__privacyleft__polcy
          =link_to "", class: "privacyleft" do
            プライバシーポリシー
        .footer__bottom__area__privacyleft__userule
          =link_to "", class: "privacyleft" do
            メルカリ利用規約
        .footer__bottom__area__privacyleft__rule
          =link_to "", class: "privacyleft" do
            あんしんスマホサポート制度に関する利用特約
        .footer__bottom__area__privacyleft__compla
          =link_to "", class: "privacyleft" do
            コンプライアンスポリシー
        .footer__bottom__area__privacyleft__mercari
          @2019 Mercari
      .footer__bottom__area__privacyright
        .footer__bottom__area__privacyright__direction
          =link_to "", class: "privacyright" do
            個人データの安全管理に係る基本方針
        .footer__bottom__area__privacyright__notation
          =link_to "", class: "privacyright" do
            特定商取引に関する表記
        .footer__bottom__area__privacyright__display
          =link_to "", class: "privacyright" do
            資金決済法に基づく表示
        .footer__bottom__area__privacyright__law
          =link_to "", class: "privacyright" do
            法令遵守と犯罪防止のために
      .footer__bottom__area__country
        .footer__bottom__area__country__title
          =link_to "", class: "country" do
            国 
        .footer__bottom__area__country__language
          .footer__bottom__area__country__language__japan
            =link_to "", class: "country" do
              日本
          .footer__bottom__area__country__language__english
            =link_to "", class: "country" do
              United States
        .footer__bottom__area__country__logos
          .footer__bottom__area__country__logos__logowhite
          .footer__bottom__area__country__logos__mercari
            @2019 Mercari
  

app/views/shared/_header.html.haml
.header
  .header__top
    .header__top__contents
      =link_to root_path,class: "logo" do
        .header__top__contents__logo
      .header__top__contents__icons
        .header__top__contents__icons__bell
          =link_to "", class: "menu" do
            = icon("far", "bell",class:"bell")
        .header__top__contents__icons__check
          =link_to "", class: "menu" do
            = icon("fas", "check",class:"check")
        .header__top__contents__icons__mypage
          =link_to "", class: "menu" do
            .header__top__contents__icons__mypage__thumbnail
    .header__top__search
      = search_form_for Product.ransack, url: search_products_path ,html: { method: :post } do |f|
        .field
          = f.search_field :name_cont,placeholder: "何かお探しですか？" ,class: 'search'
          = f.submit "",class:'submit', name: nil
          = icon("far", "search",class:"search-icon")
  .header__bottom
    .header__bottom__category
      =link_to "", class: "menu" do
        = icon("fas", "list-ul",class:"list")
        カテゴリーから探す
    .header__bottom__brand
      =link_to "", class: "menu" do
        = icon("fas", "tag",class:"tag")
        ブランドから探す
    - if user_signed_in?    
      .header__bottom__iine
        =link_to "", class: "menu" do
          = icon("far", "heart",class:"heart")
          いいね！一覧
      .header__bottom__news
        =link_to "", class: "menu" do
          = icon("far", "bell",class:"bell")
          お知らせ
      .header__bottom__todo
        .header__bottom__todo__icon
          =link_to "", class: "menu" do
            = icon("fas", "check",class:"check")
        .header__bottom__todo__text
          =link_to "", class: "menu" do
            やることリスト
      .header__bottom__mypage
        =link_to "", class: "menu" do
          .header__bottom__mypage__thumbnail
        =link_to users_mypage_path, class: "menu" do
          .header__bottom__mypage__user
            マイページ
    - else
      .header__bottom__user-registration
        =link_to  new_user_registration_path, class: "btn-red" do
          新規会員登録
      .header__bottom__user-login
        =link_to  new_user_session_path, class: "btn-login" do
          ログイン
    

app/views/shared/_navigations.html.haml
%nav.nav
  %ul.nav__lists
    %li.nav__lists__list{style: "background-color: #eee; font-weight: bold;"}
      = link_to "#", class: "nav__lists__list__link" do
        マイページ
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        お知らせ
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        やることリスト
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        いいね！一覧
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to new_product_path, class: "nav__lists__list__link" do
        出品する
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        出品した商品 - 出品中
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        出品した商品 - 取引中
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        出品した商品 - 過去の取引
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        ニュース一覧
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        評価一覧
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        ガイド
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        お問い合わせ
        = fa_icon 'chevron-right'
  %h3.nav__head
    メルペイ
  %ul.nav__lists
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        売上・振込申請
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        ポイント
        = fa_icon 'chevron-right'
  %h3.nav__head
    設定
  %ul.nav__lists
    %li.nav__lists__list
      = link_to user_path(current_user.id), name: "prof", class: "nav__lists__list__link" do
        プロフィール
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        発送元・お届け先住所変更
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to users_credit_confirmation_path, class: "nav__lists__list__link" do
        支払い方法
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        メール/パスワード
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to users_mypage_identification_path, class: "nav__lists__list__link" do
        本人情報
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to "#", class: "nav__lists__list__link" do
        電話番号の確認
        = fa_icon 'chevron-right'
    %li.nav__lists__list
      = link_to users_sign_out_path, class: "nav__lists__list__link" do
        ログアウト
        = fa_icon 'chevron-right'

app/views/shared/_sign_up_footer.html.haml
.signup-footer
  .signup-footer__top
    .signup-footer__top__polcy
      =link_to "", class: "signup" do
        プライバシーポリシー
    .signup-footer__top__rule
      =link_to "", class: "signup" do
        メルカリ利用規約
    .signup-footer__top__notation
      =link_to "", class: "signup" do
        特定商取引に関する表記
  .signup-footer__logo
  .signup-footer__mercari
    © 2019 Mercari

app/views/shared/_sign_up_header.html.haml
.signup-header
  .signup-header__block
  .signup-header__area
    .signup-header__area__logo
    .signup-header__area__figure
      .signup-header__area__figure__infomation
        .signup-header__area__figure__infomation__title
          会員情報
        .signup-header__area__figure__infomation__under
          .signup-header__area__figure__infomation__under__dot
          .signup-header__area__figure__infomation__under__bar

      .signup-header__area__figure__sms
        .signup-header__area__figure__sms__title
          電話番号認証
        .signup-header__area__figure__sms__under
          .signup-header__area__figure__sms__under__dot
          .signup-header__area__figure__sms__under__bar

      .signup-header__area__figure__address
        .signup-header__area__figure__address__title
          お届け先住所
        .signup-header__area__figure__address__under
          .signup-header__area__figure__address__under__dot
          .signup-header__area__figure__address__under__bar

      .signup-header__area__figure__payment
        .signup-header__area__figure__payment__title
          支払い方法
        .signup-header__area__figure__payment__under
          .signup-header__area__figure__payment__under__dot
          .signup-header__area__figure__payment__under__bar
      .signup-header__area__figure__complete
        .signup-header__area__figure__complete__title
          完了
        .signup-header__area__figure__complete__under
          .signup-header__area__figure__complete__under__dot