config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',  
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'products#index'

  get '/users/mypage', to: 'users#mypage'
  get '/users/sign_out', to: 'users#sign_out'

  get '/users/information', to: 'users#information'
  get '/users/sms_confirmation', to: 'users#sms_confirmation'
  post '/users/sms_confirmation', to: 'users#sms_confirmation'
  get '/users/address', to: 'users#address'
  post '/users/address', to: 'users#address'
  get '/users/payment', to: 'users#payment'
  post '/users/payment', to: 'users#payment'
  get '/users/complete', to: 'users#complete'
  post '/users/complete', to: 'users#complete'

  get '/users/mypage/identification', to: 'users#identification'
  get '/users/credit_confirmation', to: 'users#credit_confirmation'
  get '/users/:id', to: "profile#edit"
  patch '/users/:id', to: "profile#create"


  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      match 'search' => 'products#search', via: [:get, :post]
    end
    resources :purchase, only: [:new, :create] 
  end

  resources :users, except: :show
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images,allow_destroy: true, reject_if: :all_blank

  # has_many :comments
  # has_many :users through: :comments
  has_one :purchase

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size
  belongs_to_active_hash :condition
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :shipping_method
  belongs_to_active_hash :prefecture_from
  belongs_to_active_hash :shipping_days
  belongs_to :category

  

  def previous
    Product.where("id < ?",id).order("id DESC").first
  end


  def next
    Product.where("id > ?",id).order("id ASC").first
  end

  validates :name, presence: true, length: { maximum: 40 }
  validates :detail, presence: true, length: { maximum: 1000 }
  validates :category_id, presence: true
  validates :size_id, presence: true
  validates :condition_id, presence: true
  validates :delivery_fee_id, presence: true
  validates :shipping_method_id, presence: true
  validates :prefecture_from_id, presence: true
  validates :shipping_days_id, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates :user_id, presence: true
  validates :status, presence: true
  validates :images, presence:true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def new
    @product = Product.new
    @product.images.build
    @parents = Category.all.order("id ASC").limit(13)

    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end
  
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
  #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.valid?
      if @product.save!
      else
        redirect_to new_product_path
      end
    else
      @messages = @product.errors.full_messages
      flash[:error] = []
      @messages.each do |message|
        flash[:error] << message
      end
      redirect_to new_product_path
    end
    
  end

  def edit
    @product = Product.find(params[:id])
    # @images = @product.images
    @parents = Category.all.order("id ASC").limit(13)
  end

  def update
    @product = Product.find(params[:id])
    binding.pry
    # @images = @product.images
    if @product.update(product_params)
      # params[:images][:image].each do |image|
      #   @product.images.update(image: image, product_id: @product.id)
        redirect_to root_path
      # end
    else
      redirect_to new_product_path
    end
  end
    
  def index
    @ledies = Product.ransack(category_ancestry_start: "1/").result.order(id: :desc).limit(4)
    @mens = Product.ransack(category_ancestry_start: "2/").result.order(id: :desc).limit(4)
    @kids = Product.ransack(category_ancestry_start: "3/").result.order(id: :desc).limit(4)
    @cosme = Product.ransack(category_ancestry_start: "7/").result.order(id: :desc).limit(4)
    @syanera = Product.ransack(brand_cont: "シャネラ").result.order(id: :desc).limit(4)
    @ruibiton = Product.ransack(brand_cont: "ルイビトン").result.order(id: :desc).limit(4)
    @syupurinmu = Product.ransack(brand_cont: "シュプリンム").result.order(id: :desc).limit(4)
    @naiko = Product.ransack(brand_cont: "ナイコ").result.order(id: :desc).limit(4)
  end
  
  def show
    @product = Product.find(params[:id])
    @first_product=Product.first
    @last_product=Product.last
    @same_category_products = Product.where(category_id: @product.category_id).where.not(id:@product.id).order('created_at DESC').limit(6)
    @category=Category.all
    @other_products = @product.user.products.where.not(id: @product.id)
  end

  def search
    if params[:q].present?
      @search = Product.ransack(search_params)
      @products = @search.result.page(params[:page]).per(132).order(id: :desc)
      @products0 = Product.all.limit(24).order(id: :desc)
    else
      params[:q] = { sorts: 'id desc' }
      @search = Product.ransack()
      @products = Product.page(params[:page]).per(132).order(id: :desc)
    end
  end

  def delete
    product = Product.find(params[:id])
      if product.user_id == current_user.id
        product.destroy
      end
  end

  def destroy
    product = Product.find(params[:id])
      if product.user_id == current_user.id
        product.destroy
      end
    redirect_to root_path
  end
  
  private

  def product_params
    params.require(:product).permit(:name,:detail,:user_id,:size_id,:brand,:condition_id,:delivery_fee_id,:shipping_method_id,:prefecture_from_id,:shipping_days_id,:price,:status,:category_id,images_attributes: [:image, :id,:_destroy])
  end

  
  def search_params
    params.require(:q).permit!
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.haml
= link_to product_path(product.id),class: "contents__pickup__items__box__contents__link" do
  .seach__seachbox__seachlist__seacharea__cards
    .seach__seachbox__seachlist__seacharea__cards__image
      = image_tag product.images.first.image.url, size:'167x160'
    .seach__seachbox__seachlist__seacharea__cards__title
      = product.name
    .seach__seachbox__seachlist__seacharea__cards__footer
      .seach__seachbox__seachlist__seacharea__cards__footer__price
        ¥
        = product.price
      .seach__seachbox__seachlist__seacharea__cards__footer__iine
        = icon("far", "heart",class:"heart")
        15

app/views/products/edit.html.haml
.product_input
  %noscript
    %iframe{:height => "0", :src => "https://www.googletagmanager.com/ns.html?id=GTM-KLPT5L5", :style => "display:none;visibility:hidden", :width => "0"}
  .exhibition-wrap
    %header.exhibition-header
      %h1
        = link_to products_path do
          = image_tag asset_path('logo.svg?863303983')
        
    %main.exhibition-main
      %section.l-exhibition-container
        #sell-container
          %div{"data-reactroot" => ""}
            .sell-container-inner
              %h2.sell-container-inner__head 商品の情報を入力
              - unless flash[:error].blank?
                - flash[:error].each do |msg|
                  = content_tag :p, msg, class: 'error-message'
              = form_with model: @product, class:'sell-form sell-container-inner__form dropzone', id: "item-dropzone",local: true do |form|
                .sell-upload-box
                  %h3.sell-upload-box__head
                    出品画像
                    %span.form-require 必須
                  %p 最大10枚までアップロードできます
                  .sell-upload-box__container.clearfix.state-image-number-10
                    .upload-items
                      .image_box_multi
                        .upload-items
                          - @product.images.each_with_index do |img, i|
                            .update__img-view{"data-image" => i}
                              = image_tag img.image.url, size: "110x110", class: "image_box_multi2 img_view__inner", style: "display: flex;"
                              .btn_wrapper
                                .edit-btn 編集
                                .update__delete-btn 削除 
                      .image_box_multi2
                    .image-upload-box
                      .dropzone-container.clearfix
                        #preview
                        = form.fields_for :images do |image|
                          .dropzone-area
                            = image.label :image,class:"upload-items-drop-box have-item-0 dropzone-box",for: "upload-image" do
                              .delete_box
                                = image.label '削除'
                                = image.check_box :_destroy
                                .input_area
                                  = image.file_field :image,multiple: true,name: "product[images_attributes][0][image]",class:'upload-items-drop-box__file upload-image',id: "upload-image",'data-image': 0
                                %pre.upload-items-drop-box__drop
                                  :preserve
                                    ドラッグアンドドロップ
                                    またはクリックしてファイルをアップロード
                                %i.upload-items-drop-box__icon
                          #preview2
                          .dropzone-area2
                            = image.label :image, class: "dropzone-box", for: "upload-image" do
                              %p ここをクリックしてください
                    .image-upload-box2
                      = form.fields_for :images do |i|
                        .dropzone-container.clearfix
                          #preview
                          .dropzone-area
                            = i.label :image,class:"upload-items-drop-box have-item-0 dropzone-box",for: "upload-image" do
                              .input_area
                                = i.file_field :image,multiple: true,name: "product[images_attributes][0][image]",class:'upload-items-drop-box__file upload-image',id: "upload-image",'data-image': 0
                              %pre.upload-items-drop-box__drop
                                :preserve
                                  ドラッグアンドドロップ
                                  またはクリックしてファイルをアップロード
                              %i.upload-items-drop-box__icon
                .sell-content
                  .sell-content__form--top.form-group
                    %label
                      商品名
                      %span.form-require 必須
                    %div
                      //商品名の入力フォーム
                      = form.text_field :name,class:"input-default",placeholder:"商品名（必須 40文字まで)"
                  .sell-content__form--bottom.form-group
                    %label
                      商品の説明
                      %span.form-require 必須
                    //商品詳細のフォーム
                    = form.text_area :detail,class:"textarea-default textarea-detail",placeholder:"商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。",rows: 5
                .sell-content.clearfix
                  %h3.sell-content__head.sell-sub-head 商品の詳細
                  .sell-content__form.sell-form-box
                    .form-group
                      %label
                        カテゴリー
                        %span.form-require 必須
                      %div.category_form
                        .select-wrap
                          %i.fas.fa-chevron-down
                          = form.collection_select :category_id, Category.where(id: 1..13), :id, :name,class:"select-default category_id",prompt: "---"
                    .form-group
                      %label
                        商品の状態
                        %span.form-require 必須
                      %div
                        .select-wrap
                          %i.fas.fa-chevron-down
                          = form.collection_select :condition_id, Condition.all, :id, :name,class:"select-wrap",prompt: "---"
                .sell-content.clearfix
                  %h3.sell-content__head.sell-sub-head 配送について
                  %a.sell-content__form.form-question{:href => "/jp/help_center/article/68/", :target => "_blank"} ?
                  .sell-form-box
                    .form-group.delivery_fee_box
                      %label
                        配送料の負担
                        %span.form-require 必須
                      .select-wrap
                        %i.fas.fa-chevron-down
                        = form.collection_select :delivery_fee_id, DeliveryFee.all, :id, :name,class:"select-default",prompt: "---"
                    .form-group
                      %label
                        発送元の地域
                        %span.form-require 必須
                      .select-wrap
                        %i.fas.fa-chevron-down
                        = form.collection_select :prefecture_from_id, PrefectureFrom.all, :id, :name,class:"select-default",prompt: "---"
                    .form-group
                      %label
                        発送までの日数
                        %span.form-require 必須
                      .select-wrap
                        %i.fas.fa-chevron-down
                        = form.collection_select :shipping_days_id, ShippingDays.all, :id, :name,class:"select-default",prompt: "---"
                .sell-content.clearfix
                  %h3.sell-content__head.sell-sub-head 販売価格(300〜9,999,999)
                  %a.sell-content__form.form-question{:href => "/jp/help_center/article/64/", :target => "_blank"} ?
                  .sell-form-box
                    %ul.sell-form-box__price
                      %li.form-group
                        .clearfix
                          %label.l-left
                            価格
                            %span.form-require 必須
                          .l-right.sell-price-input
                            %span.yen ¥
                            %span.price-box
                              = form.number_field :price,class:"input-default",placeholder:"例）300"
                      %li.clearfix
                        .l-left
                          販売手数料 (10%)
                        #commission.l-right -
                      %li.clearfix.bold
                        .l-left 販売利益
                        #price.l-right -
                .modal.is-show{role: "dialog", tabindex:"-1"}
                  .modal-inner
                    %div
                      %h3.modal-head 出品が完了しました
                      .sell-modal-body{"data-gtm-vis-first-on-screen-6824027_198" => "42356", "data-gtm-vis-has-fired-6824027_198" => "1", "data-gtm-vis-recent-on-screen-6824027_198" => "42356", "data-gtm-vis-total-visible-time-6824027_198" => "100"}
                        / react-text: 880
                        あなたが出品した商品は「出品した商品一覧」からいつでも見ることができます。
                        / /react-text
                        =link_to "続けて出品する", new_product_path, class: "btn-default btn-red"
                        %p.text-center
                          =link_to "商品ページへ行ってシェアする", root_path
                .sell-content.sell-btn-box
                  %div
                    %p
                      =link_to "禁止されている出品",'https://www.mercari.com/jp/help_center/getting_started/prohibited_items/',target: "_blank"
                      、
                      =link_to "行為",'https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/',target: "_blank"
                      を必ずご確認ください。
                    %p
                      またブランド品でシリアルナンバー等がある場合はご記載ください。
                      =link_to "偽ブランドの販売","https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/",target: "_blank"
                      は犯罪であり処罰される可能性があります。
                    %p
                      また、出品をもちまして
                      =link_to "加盟店規約","https://www.mercari.com/jp/seller_terms/",target: "_blank"
                      に同意したことになります。
                  %div
                    -# statusに初期状態である0（未売却）を入れる
                    = form.hidden_field :status, value: 0
                    = form.submit "出品する", class:"btn-default btn-red exhibition_submit"
                  %a.btn-default.btn-gray
                    もどる
              
              .overlay
    %footer.exhibition-footer
      %nav
        %ul.clearfix
          %li
            %a{:href => "https://www.mercari.com/jp/privacy/"} プライバシーポリシー
          %li
            %a{:href => "https://www.mercari.com/jp/tos/"} メルカリ利用規約
          %li
            %a{:href => "https://www.mercari.com/jp/tokutei/"} 特定商取引に関する表記
      %a.single-footer-logo
        %div.LogoGray= image_tag asset_path('logo-gray.svg')
      %p
        %small © 2019 Mercari

app/views/products/search.html.haml
= render 'shared/header'
= render 'shared/exhibitation'

- if @products.total_count == 0
  .seach
    .seach__seachbox
      = render 'products/searchbar'
      .seach__seachbox__seachlist
        .seach__seachbox__seachlist__logo
          .seach__seachbox__seachlist__logo__word
            = params[:q][:name_cont]
          .seach__seachbox__seachlist__logo__result
            の検索結果
        .seach__seachbox__seachlist__noproduct
          該当する商品が見つかりません。検索条件を変えて、再度お試しください。
        .seach__seachbox__seachlist__new
          新着商品
        .seach__seachbox__seachlist__seacharea
          = render partial: 'products/product', collection: @products0

- else 
  .seach
    .seach__seachbox
      = render 'products/searchbar'
      .seach__seachbox__seachlist
        .seach__seachbox__seachlist__logo
          -if params[:q].present? && params[:q][:name_cont].present?
            .seach__seachbox__seachlist__logo__word
              = params[:q][:name_cont]
            .seach__seachbox__seachlist__logo__result
              の検索結果
          -else
            .seach__seachbox__seachlist__logo__word
              新着商品
        .seach__seachbox__seachlist__number
          = page_entries_info @products
        .seach__seachbox__seachlist__seacharea
          = render partial: 'products/product', collection: @products
        .seach__seachbox__seachlist__pagenation
          = paginate @products



= render 'shared/footer'

app/views/products/show.html.haml
= render 'shared/header'
= render 'shared/exhibitation'
.wrapper1
  %section.item-container1
    %h1.item-container1__item-name 
      = @product.name
    .item-container1__item-content.clearfix
      .content--photo 
        .content--photo-up
          = image_tag @product.images.first.image.url, size: "300x300", class:"mainimage img01"
        %ul.subimage.img01
          - @product.images.each do |image|
            %li.picture
              = image_tag image.image.url, size: "60x60", class:"boxshow"
      %table.content--detail-table
        %tbody.table
          %tr.table--section
            %th.table--section-left 出品者
            %th.table--section-right-blue 
              = link_to "#{@product.user.nickname}", users_mypage_path, method: :get,class:"blue"
              = image_tag asset_path('sampleicon.png'), size: "130x25"
          %tr.table--section
            %th.table--section-left カテゴリー
            %th.table--section-right-blue 
              = link_to '#',class:"blue" do
                - parent=@product.category.path_ids[0].to_i
                = @category.find(parent).name
              %br  
              = link_to '#',class:"blue" do
                %i.fas.fa-angle-right 
                - child=@product.category.path_ids[1].to_i
                = @category.find(child).name 
                 
              %br 
              = link_to '#',class:"blue" do
                %i.fas.fa-angle-right 
                - grandchild=@product.category.path_ids[2].to_i
                = @category.find(grandchild).name
                 
          //params[:id]で取得したidの商品に対してcategory子、孫も表示するために記載//
          %tr.table--section
            %th.table--section-left ブランド
            %th.table--section-right-blue 
              = @product.brand
              = link_to '',class: "table--section-right-blue "
          %tr.table--section
            %th.table--section-left 商品状態
            %th.table--section-right 
              = @product.condition.name
          %tr.table--section
            %th.table--section-left 配送料負担
            %th.table--section-right 
              = @product.delivery_fee.name
          %tr.table--section
            %th.table--section-left 配送方法
            %th.table--section-right 
              = @product.shipping_method.name
          %tr.table--section
            %th.table--section-left 配送元
            %th.table--section-right-blue 
              = @product.prefecture_from.name
          %tr.table--section
            %th.table--section-left 配送日目安
            %th.table--section-right
              = @product.shipping_days.name
        // 上記 brand,categoryからクリックすると本物のメルカリではcategory show pageに遷移するが今の時点では割愛する//     
    .item-container1__item-price
      .test
        %span.item-container1__item-price-bold  ¥
        = @product.price.to_s(:delimited)
        %span.item-container1__item-price-tax (税込)
        %span.item-container1__item-price-shipping-fee 送料込み
    - unless user_signed_in? && @product.user.id == current_user.id
      = link_to " 購入画面に進む", new_product_purchase_path(@product.id),  class:"item-container1__item-buy-btn"
    .item-container1__item-description 
      %p.item-description-inner
        = @product.detail

    - unless user_signed_in? && @product.user.id == current_user.id
      .item-container1__item-other-btn.clearfix
        .link_btn_left
          %button.item-other-btn-left 
            %i.fa.fa-heart いいね！
          %button#btn.item-other-btn-left  不適切な商品の勧告
        .link_btn_right
          %i.fa.fa-lock 
          = link_to 'あんしん・あんぜんへの取り組み', root_path, class: 'item-other-btn-right'

  - if user_signed_in? && @product.user.id == current_user.id
    %section.item-container1
      = link_to "商品の編集", edit_product_path(@product.id), class: "item-container1__item-edit-btn"
      or
      = link_to "出品を一旦停止する", '#', class: "item-container1__item-suspend-btn"
      = link_to "この商品を削除する", product_path(@product.id), method: :delete, class: "item-container1__item-delete-btn"

  .item-detail-message
    .message-container
      .message-content
        %form.message-form{:action => "https://www.mercari.com/jp/comment/add/", :method => "POST"}
          %input{:name => "__csrf_value", :type => "hidden", :value => "c55239470129d9454965bb6e795b3c51b1a2c574b8adf51df04606f58bd8d41724a694229487bce3caa8a08b5537a8923c9f042e751656ccf095b59342b60d381"}/
          %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %input{:name => "item_id", :type => "hidden", :value => "m42713469142"}/
          %input{:name => "redirect_url_key", :type => "hidden", :value => "item_detail"}/
          %textarea.textarea-default{:name => "body", :type => "text", :value => ""}
          %button.message-submit.btn-default.btn-gray{:type => "submit"}
            %span コメントする
  %ul.item-nav.clearfix
    %li.item-nav__link
      = link_to '< Preview product', product_path(@product.previous), class: 'item-nav__link-prev' unless @product.id == @first_product.id
      = link_to 'Next product >', product_path(@product.next), class: 'item-nav__link-next' unless @product.id == @last_product.id
 
  .sns
    %ul.sns--icon
      %i.fab.fa-facebook-square
      %i.fab.fa-twitter-square
      %i.fab.fa-line
      %i.fab.fa-pinterest-square
  .item-others
    - unless @other_products.blank?
      %section.item-others--seller
        %h2.item-others-seller-name 
          = @product.user.nickname 
          さんのその他の商品
        .item-others--seller_product
          - @product.user.products.each do |product_other|
            - unless product_other.id == @product.id
              = link_to product_path(product_other.id),class: "contents__pickup__items__box__contents__link" do
                .items-box
                  .items-box_photo
                    = image_tag("#{product_other.images.first.image.url}", size: "220x220")
                  .items-box_body
                    %h3.items-box-name
                      =product_other.name
                    .items-box-num
                      .items-box-price ￥
                      =product_other.price.to_s(:delimited, delimiter: ',')
                      .items-box-icon
                        %i.fa.fa-heart
                        1

    - unless @same_category_products.blank?
      %section.item-others--product
        %h2.item-others--product__category-name
          =@product.category.name
          その他の商品
        .item-others--product__content
        - @same_category_products.each do |product|
          = link_to product_path(product.id),class: "contents__pickup__items__box__contents__link" do
            .items-box
              .items-box_photo=image_tag("#{product.images.first.image.url}", size: "220x220")
              .items-box_body
                %h3.items-box-name
                  = product.name
                .items-box-num
                  .items-box-price ￥
                  = product.price.to_s(:delimited, delimiter: ',')
                  .items-box-icon
                    %i.fa.fa-heart
                    2
        
= render 'shared/footer'

// 下の記述は[不適切な商品の勧告]をクリックした時にmodalを表示させる

#modal.modal
  .modal-content
    .modal-body
      .modal-head.bold 確認
      %h1 不適切な商品を報告しますか？
    .modalbtnbox
      %button#closeBtn.modal-btn.modal-btn-cancel{"data-close" => "modal"} キャンセル
      %button.modal-btn.modal-btn-submit はい  